load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "hash_funcs",
    srcs = ["hash_funcs.cc"],
    hdrs = ["hash_funcs.h"],
    visibility = ["//load_balancing_and_hashing/main:__pkg__"]
)